[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "32e4fbe8b1fcd3276c044793262b1849d62a7ff3e3fec08f446c344cfa325544"
client_id = "614373096676-b9vq3rilugvsf51vcr9e1avisjel5t8n.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"